### ISSUE TITLE
CPU only code for inference with DetectNet

### ISSUE THREAD

**Issue by ShervinAr** [Abaco-Systems/jetson-inference-gv#1]
Hello,

Thanks for all the codes you shared. Is there any chance you could provide some C++ source code for DetectNet Inference using _only_ **_CPU_** and not _**GPU**_?

many thanks,
Shervin

**Comment by ghost** [comment]
Unfortunately the ARM CPU on my TX1 would under perform compared to the GPU so I'm not going to go there with a CPU implementation. Most of this code originated from Nvidia who want to sell GPUs so I don't expect them to be supporting CPU implementations any time soon.
