### ISSUE TITLE
mean value in detectNet.cpp

### ISSUE THREAD

**Issue by ShervinAr** [Abaco-Systems/jetson-inference-gv#2]
Hello,

I got a question regarding the mean value used in detectNet.cpp: the mean value seems to be set to "104.0069879317889f, 116.66876761696767f, 122.6789143406786f", line 164 in detetNet.cpp, regardless of the trained model. Shouldn't this value be a variable and read from the mean.binaryproto data file?

many thanks,
Shervin

**Comment by ghost** [comment]
I'm focusing my efforts on imagenet although I have ported the camera support over to detectnet. You might want to contact the original author of the project dusty-nvidia for comment. I wont have time to flush out issues with detectnet any time soon but if you find problems and manage to fix them Ill be happy to incorporate them into this fork.
